version: 2.1

orbs:
  maven: circleci/maven@1.3.0

executors:
  j8:
    docker:
      - image: cimg/openjdk:8.0
jobs:
  build:
    executor: j8
    steps:
      - checkout
      - maven/with_cache:
          steps:
            - run: java -XX:+PrintFlagsFinal -version
            - run: mvn --version
            - run: mvn verify --update-snapshots --settings .travis.settings.xml -e
      - maven/process_test_results
workflows:
  build:
    when:
      not:
        equal: [ tools, << pipeline.git.branch >> ]
    jobs:
      - build
